# Generated by Django 5.1.7 on 2025-06-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('depto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depto.depto')),
            ],
        ),
    ]
